version: "3"

services:
  postgres:
    image: postgres:14
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  client:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - APP_SCOPE=client
    env_file:
      - apps/client/.env

  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - APP_SCOPE=web
    env_file:
      - apps/web/.env
    ports:
      - "3000:3000"

volumes:
  postgres_data:
