// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType & DisallowNamespaces
export type BaseLocale = 'en-US'

export type Locales =
	| 'en-US'
	| 'pt-BR'

export type Translation = RootTranslation & DisallowNamespaces

export type Translations = RootTranslation &
{
	SLASH: NamespaceSLASHTranslation
}

type RootTranslation = {
	/**
	 * H​i​ ​{​n​a​m​e​}​!​ ​P​l​e​a​s​e​ ​l​e​a​v​e​ ​a​ ​s​t​a​r​ ​i​f​ ​y​o​u​ ​l​i​k​e​ ​t​h​i​s​ ​p​r​o​j​e​c​t​:​ ​h​t​t​p​s​:​/​/​g​i​t​h​u​b​.​c​o​m​/​m​a​u​r​i​c​i​o​b​r​a​z​/​d​i​s​c​o​r​d​.​t​s​-​m​o​n​o​r​e​p​o
	 * @param {string} name
	 */
	HI: RequiredParams<'name'>
	/**
	 * T​h​i​s​ ​i​s​ ​a​n​ ​e​x​a​m​p​l​e​ ​o​f​ ​a​ ​m​e​s​s​a​g​e​ ​w​i​t​h​ ​I​1​8​n​ ​s​u​p​p​o​r​t​.
	 */
	EXAMPLE_MESSAGE: string
	/**
	 * C​u​r​r​e​n​t​l​y​ ​y​o​u​ ​h​a​v​e​ ​{​t​o​d​o​s​C​o​u​n​t​}​ ​t​o​d​o​s​ ​i​n​ ​y​o​u​r​ ​l​i​s​t​.​
​
​{​t​o​d​o​s​}
	 * @param {string} todos
	 * @param {number} todosCount
	 */
	TODOS_LIST_TODOS: RequiredParams<'todos' | 'todosCount'>
	/**
	 * Y​o​u​ ​h​a​v​e​ ​n​o​ ​t​o​d​o​s​ ​y​e​t​.​ ​U​s​e​ ​`​/​t​o​d​o​s​ ​a​d​d​`​ ​t​o​ ​a​d​d​ ​o​n​e​.
	 */
	TODOS_LIST_TODOS_NO_TODOS: string
	/**
	 * T​o​d​o​ ​a​d​d​e​d​ ​s​u​c​c​e​s​s​f​u​l​l​y​ ​w​i​t​h​ ​s​l​u​g​ ​`​{​s​l​u​g​}​`​.
	 * @param {string} slug
	 */
	TODOS_ADD_TODO_SUCCESS: RequiredParams<'slug'>
	/**
	 * T​o​d​o​ ​r​e​m​o​v​e​d​ ​s​u​c​c​e​s​s​f​u​l​l​y​.
	 */
	TODOS_REMOVE_TODO_SUCCESS: string
	/**
	 * T​o​d​o​ ​n​o​t​ ​f​o​u​n​d​.
	 */
	TODOS_TODO_NOT_FOUND: string
	/**
	 * T​o​d​o​ ​s​e​t​ ​a​s​ ​c​o​m​p​l​e​t​e​d​ ​s​u​c​c​e​s​s​f​u​l​l​y​.
	 */
	TODOS_COMPLETE_TODO_SUCCESS: string
	/**
	 * T​o​d​o​ ​s​e​t​ ​a​s​ ​u​n​c​o​m​p​l​e​t​e​d​ ​s​u​c​c​e​s​s​f​u​l​l​y​.
	 */
	TODOS_UNCOMPLETE_TODO_SUCCESS: string
}

export type NamespaceSLASHTranslation = {
	/**
	 * t​o​d​o​s
	 */
	TODOS_NAME: string
	/**
	 * C​o​m​m​a​n​d​s​ ​t​o​ ​m​a​n​a​g​e​ ​y​o​u​r​ ​t​o​d​o​s​.
	 */
	TODOS_DESCRIPTION: string
	/**
	 * s​l​u​g
	 */
	TODOS_OPTION_SLUG_NAME: string
	/**
	 * T​h​e​ ​s​l​u​g​ ​o​f​ ​t​h​e​ ​t​o​d​o​.
	 */
	TODOS_OPTION_SLUG_DESCRIPTION: string
	/**
	 * l​i​s​t
	 */
	TODOS_LIST_TODOS_NAME: string
	/**
	 * L​i​s​t​ ​a​l​l​ ​y​o​u​r​ ​t​o​d​o​s​.
	 */
	TODOS_LIST_TODOS_DESCRIPTION: string
	/**
	 * a​d​d
	 */
	TODOS_ADD_TODO_NAME: string
	/**
	 * A​d​d​ ​a​ ​t​o​d​o​.
	 */
	TODOS_ADD_TODO_DESCRIPTION: string
	/**
	 * t​i​t​l​e
	 */
	TODOS_ADD_TODO_OPTION_TITLE_NAME: string
	/**
	 * T​h​e​ ​t​i​t​l​e​ ​o​f​ ​t​h​e​ ​t​o​d​o​.
	 */
	TODOS_ADD_TODO_OPTION_TITLE_DESCRIPTION: string
	/**
	 * r​e​m​o​v​e
	 */
	TODOS_REMOVE_TODO_NAME: string
	/**
	 * R​e​m​o​v​e​ ​a​ ​t​o​d​o​.
	 */
	TODOS_REMOVE_TODO_DESCRIPTION: string
	/**
	 * c​o​m​p​l​e​t​e
	 */
	TODOS_COMPLETE_TODO_NAME: string
	/**
	 * C​o​m​p​l​e​t​e​ ​a​ ​t​o​d​o​.
	 */
	TODOS_COMPLETE_TODO_DESCRIPTION: string
	/**
	 * u​n​c​o​m​p​l​e​t​e
	 */
	TODOS_UNCOMPLETE_TODO_NAME: string
	/**
	 * U​n​c​o​m​p​l​e​t​e​ ​a​ ​t​o​d​o​.
	 */
	TODOS_UNCOMPLETE_TODO_DESCRIPTION: string
}

export type Namespaces =
	| 'SLASH'

type DisallowNamespaces = {
	/**
	 * reserved for 'SLASH'-namespace\
	 * you need to use the `./SLASH/index.ts` file instead
	 */
	SLASH?: "[typesafe-i18n] reserved for 'SLASH'-namespace. You need to use the `./SLASH/index.ts` file instead."
}

export type TranslationFunctions = {
	/**
	 * Hi {name}! Please leave a star if you like this project: https://github.com/mauriciobraz/discord.ts-monorepo
	 */
	HI: (arg: { name: string }) => LocalizedString
	/**
	 * This is an example of a message with I18n support.
	 */
	EXAMPLE_MESSAGE: () => LocalizedString
	/**
	 * Currently you have {todosCount} todos in your list.

{todos}
	 */
	TODOS_LIST_TODOS: (arg: { todos: string, todosCount: number }) => LocalizedString
	/**
	 * You have no todos yet. Use `/todos add` to add one.
	 */
	TODOS_LIST_TODOS_NO_TODOS: () => LocalizedString
	/**
	 * Todo added successfully with slug `{slug}`.
	 */
	TODOS_ADD_TODO_SUCCESS: (arg: { slug: string }) => LocalizedString
	/**
	 * Todo removed successfully.
	 */
	TODOS_REMOVE_TODO_SUCCESS: () => LocalizedString
	/**
	 * Todo not found.
	 */
	TODOS_TODO_NOT_FOUND: () => LocalizedString
	/**
	 * Todo set as completed successfully.
	 */
	TODOS_COMPLETE_TODO_SUCCESS: () => LocalizedString
	/**
	 * Todo set as uncompleted successfully.
	 */
	TODOS_UNCOMPLETE_TODO_SUCCESS: () => LocalizedString
	SLASH: {
		/**
		 * todos
		 */
		TODOS_NAME: () => LocalizedString
		/**
		 * Commands to manage your todos.
		 */
		TODOS_DESCRIPTION: () => LocalizedString
		/**
		 * slug
		 */
		TODOS_OPTION_SLUG_NAME: () => LocalizedString
		/**
		 * The slug of the todo.
		 */
		TODOS_OPTION_SLUG_DESCRIPTION: () => LocalizedString
		/**
		 * list
		 */
		TODOS_LIST_TODOS_NAME: () => LocalizedString
		/**
		 * List all your todos.
		 */
		TODOS_LIST_TODOS_DESCRIPTION: () => LocalizedString
		/**
		 * add
		 */
		TODOS_ADD_TODO_NAME: () => LocalizedString
		/**
		 * Add a todo.
		 */
		TODOS_ADD_TODO_DESCRIPTION: () => LocalizedString
		/**
		 * title
		 */
		TODOS_ADD_TODO_OPTION_TITLE_NAME: () => LocalizedString
		/**
		 * The title of the todo.
		 */
		TODOS_ADD_TODO_OPTION_TITLE_DESCRIPTION: () => LocalizedString
		/**
		 * remove
		 */
		TODOS_REMOVE_TODO_NAME: () => LocalizedString
		/**
		 * Remove a todo.
		 */
		TODOS_REMOVE_TODO_DESCRIPTION: () => LocalizedString
		/**
		 * complete
		 */
		TODOS_COMPLETE_TODO_NAME: () => LocalizedString
		/**
		 * Complete a todo.
		 */
		TODOS_COMPLETE_TODO_DESCRIPTION: () => LocalizedString
		/**
		 * uncomplete
		 */
		TODOS_UNCOMPLETE_TODO_NAME: () => LocalizedString
		/**
		 * Uncomplete a todo.
		 */
		TODOS_UNCOMPLETE_TODO_DESCRIPTION: () => LocalizedString
	}
}

export type Formatters = {}
