// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType & DisallowNamespaces
export type BaseLocale = 'en-US'

export type Locales =
	| 'en-US'
	| 'pt-BR'

export type Translation = RootTranslation & DisallowNamespaces

export type Translations = RootTranslation &
{
	SLASH: NamespaceSLASHTranslation
}

type RootTranslation = {
	/**
	 * H​i​ ​{​n​a​m​e​}​!​ ​P​l​e​a​s​e​ ​l​e​a​v​e​ ​a​ ​s​t​a​r​ ​i​f​ ​y​o​u​ ​l​i​k​e​ ​t​h​i​s​ ​p​r​o​j​e​c​t​:​ ​h​t​t​p​s​:​/​/​g​i​t​h​u​b​.​c​o​m​/​m​a​u​r​i​c​i​o​b​r​a​z​/​d​i​s​c​o​r​d​.​t​s​-​m​o​n​o​r​e​p​o
	 * @param {string} name
	 */
	HI: RequiredParams<'name'>
	/**
	 * T​h​i​s​ ​i​s​ ​a​n​ ​e​x​a​m​p​l​e​ ​o​f​ ​a​ ​m​e​s​s​a​g​e​ ​w​i​t​h​ ​I​1​8​n​ ​s​u​p​p​o​r​t​.
	 */
	EXAMPLE_MESSAGE: string
}

export type NamespaceSLASHTranslation = {
	/**
	 * e​x​a​m​p​l​e
	 */
	EXAMPLE_EXAMPLE_NAME: string
	/**
	 * T​h​i​s​ ​i​s​ ​a​n​ ​e​x​a​m​p​l​e​ ​c​o​m​m​a​n​d​.
	 */
	EXAMPLE_EXAMPLE_DESCRIPTION: string
}

export type Namespaces =
	| 'SLASH'

type DisallowNamespaces = {
	/**
	 * reserved for 'SLASH'-namespace\
	 * you need to use the `./SLASH/index.ts` file instead
	 */
	SLASH?: "[typesafe-i18n] reserved for 'SLASH'-namespace. You need to use the `./SLASH/index.ts` file instead."
}

export type TranslationFunctions = {
	/**
	 * Hi {name}! Please leave a star if you like this project: https://github.com/mauriciobraz/discord.ts-monorepo
	 */
	HI: (arg: { name: string }) => LocalizedString
	/**
	 * This is an example of a message with I18n support.
	 */
	EXAMPLE_MESSAGE: () => LocalizedString
	SLASH: {
		/**
		 * example
		 */
		EXAMPLE_EXAMPLE_NAME: () => LocalizedString
		/**
		 * This is an example command.
		 */
		EXAMPLE_EXAMPLE_DESCRIPTION: () => LocalizedString
	}
}

export type Formatters = {}
